
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class RideHistory extends javax.swing.JFrame {

    /**
     * Creates new form RideHistory
     * @param userName
     */
    String uid;
    public RideHistory(String userName) {
        initComponents();
        uid=userName;
        //ride.setLocation(new Point(400, 300));
    String t=null;
    try{
           Class.forName("com.mysql.cj.jdbc.Driver");
        try (Connection conner = DriverManager.getConnection("jdbc:mysql://localhost:3306/customerdetails","root","bits@123")) {
 
            PreparedStatement psb = conner.prepareStatement("select PTrips from cdetails where uName=?");
            psb.setString(1,uid);
            ResultSet rsb = psb.executeQuery();
            
            
            if (rsb.next()) {
                t=rsb.getString(1);
              
            }
              ride.setText("<html>"+t.replaceAll("\n","<br/><br/>")+"</html>");
     } 
                
            }
            
    
       catch(ClassNotFoundException | SQLException e)
       {
         JOptionPane.showMessageDialog(null,e);
       } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ride = new javax.swing.JLabel();
        returnCB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(15, 36, 94));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Past Ride Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1479, 92));

        jPanel2.setBackground(new java.awt.Color(96, 101, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 970));

        ride.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        ride.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ride.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(ride, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 920, 580));

        returnCB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        returnCB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returnCB.setText("Return to Cab Booking Portal");
        returnCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnCBMouseClicked(evt);
            }
        });
        getContentPane().add(returnCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 750, 300, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel2.setText("Driver Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 130, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel4.setText("Cab Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel5.setText("Pick");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel6.setText("Drop");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel7.setText("Fare");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 920, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnCBMouseClicked
        CabBooking cb = new CabBooking(uid);
        cb.setVisible(true);
        cb.pack();
        cb.setLocationRelativeTo(null);
        cb.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_returnCBMouseClicked

    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //try {
          //  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            //    if ("Nimbus".equals(info.getName())) {
              //      javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
  //              }
    //        }
      //  } catch (ClassNotFoundException ex) {
        //    java.util.logging.Logger.getLogger(RideHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} //catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RideHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  //      } catch (IllegalAccessException ex) {
    //        java.util.logging.Logger.getLogger(RideHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      //  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        //    java.util.logging.Logger.getLogger(RideHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //}
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
          //  public void run() {
           //     new RideHistory().setVisible(true);
            //}
      //  });
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel returnCB;
    private javax.swing.JLabel ride;
    // End of variables declaration//GEN-END:variables
}
