
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class Trip1 extends javax.swing.JFrame {

    /**
     * Creates new form Trip1
     */
    CabBooking cbk;
    int id;
    String fName;
    String lName;
    Long Phoneno;
    String drop;
    String pick;
    float amount = 0;
    String CarNo;
    float Rating;
    int trips = 0;
    String dPhoneno;
    
    public Trip1(CabBooking cb , int c, String d, float amt , String p) {
        initComponents();
        this.setLocationRelativeTo(null);
        cbk = cb;
        id = c;
        String str = Integer.toString(c);
        drop = d;
        pick = p;
        amount = amt;
        String nrating = null;
        
        try{
           Class.forName("com.mysql.cj.jdbc.Driver");
            try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/driverdetails","root","bits@123")) {
 
            PreparedStatement ps = conn.prepareStatement("select dFname, dLName ,dPhoneno, carNo, rating , Counter from drdetails  where dID=?");
            ps.setString(1,str);
            ResultSet rs = ps.executeQuery();
            
            
            
                    
            
            if (rs.next()) {
                fName = rs.getString(1);
                lName = rs.getString(2);
                Phoneno = rs.getLong(3);
                CarNo = rs.getString(4);
                Rating = rs.getFloat(5);
                nrating = String.format("%.2f", Rating);
                trips = rs.getInt(6);
                
                dPhoneno= Long.toString(Phoneno);
                dName.setText(fName + " " + lName);
                dPno.setText(dPhoneno);
                dCno.setText(CarNo);
                pickup1.setText(pick);
                Dest.setText(drop);
                tamt.setText(Float.toString(amount));
                dRating.setText(nrating);
                trips_completed.setText(Integer.toString(trips));
            }   
            PreparedStatement pstmt = conn.prepareStatement("select samay from distance  where Start=? and End = ?");
            pstmt.setString(1,pick );
            pstmt.setString(2,drop);
            
            ResultSet rstmt = pstmt.executeQuery();
            if(rstmt.next())
            {
                String time = rstmt.getString(1);
                duration.setText(time);
                
            }
                }
            }
        catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TWallet = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dPno = new javax.swing.JLabel();
        dName = new javax.swing.JLabel();
        dCno = new javax.swing.JLabel();
        Dest = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tamt = new javax.swing.JLabel();
        trips_completed = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        duration = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dRating = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pickup1 = new javax.swing.JLabel();
        returnCB = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(15, 36, 94));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("You are on your way !!!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(192, 57, 43));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 20, 130, 50));

        TWallet.setBackground(new java.awt.Color(34, 167, 240));
        TWallet.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        TWallet.setForeground(new java.awt.Color(255, 255, 255));
        TWallet.setText("Wallet");
        TWallet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TWalletActionPerformed(evt);
            }
        });
        jPanel1.add(TWallet, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, 121, 52));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Destination :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 170, 34));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Car no : ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 110, 34));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Driver Phone No : ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, 34));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Driver Name : ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 198, 34));

        dPno.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jPanel2.add(dPno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 130, 210, 40));

        dName.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jPanel2.add(dName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 70, 210, 40));

        dCno.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jPanel2.add(dCno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 200, 210, 50));

        Dest.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jPanel2.add(Dest, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 490, 210, 38));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Trip Fare :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, 150, 44));

        tamt.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jPanel2.add(tamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 560, 210, 44));

        trips_completed.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jPanel2.add(trips_completed, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 350, 210, 38));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("No of Rated Trips:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 200, 34));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Duration :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 650, 140, 44));

        duration.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jPanel2.add(duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 640, 210, 44));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Driver Rating :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 227, 44));

        dRating.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jPanel2.add(dRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 260, 210, 44));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Pickup :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 128, 34));

        pickup1.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jPanel2.add(pickup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 420, 210, 38));

        returnCB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        returnCB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returnCB.setText("Return to Cab Booking Portal");
        returnCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnCBMouseClicked(evt);
            }
        });
        jPanel2.add(returnCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 710, 300, 60));

        jPanel3.setBackground(new java.awt.Color(96, 101, 250));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 570, 950));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 690, 940, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 940, 20));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 960, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 312, 940, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 392, 950, 10));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 950, 10));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, 950, 10));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, 940, 20));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 940, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1491, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1491, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 834, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TWalletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TWalletActionPerformed
        
    Wallet wt = new Wallet(cbk);
    wt.setVisible(true);
    wt.pack();
    wt.setLocationRelativeTo(null);
    wt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();  
    }//GEN-LAST:event_TWalletActionPerformed

    private void returnCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnCBMouseClicked
       CabBooking cb = new CabBooking(cbk.userName);
        cb.setVisible(true);
        cb.pack();
        cb.setLocationRelativeTo(null);
        cb.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();   
    }//GEN-LAST:event_returnCBMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/customerdetails","root","bits@123");
            PreparedStatement pstmt;
            String str = ( "update cdetails set LStatus = ? where uName=?");
            pstmt=conn.prepareStatement(str);
            pstmt.setInt(1,0);
            pstmt.setString(2,cbk.userName);
            pstmt.execute();
        } catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        LoginPage lgp = new LoginPage();
        lgp.setVisible(true);
        lgp.pack();
        lgp.setLocationRelativeTo(null);
        lgp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
/**/
    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trip1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trip1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trip1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trip1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
*/
        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trip1().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dest;
    private javax.swing.JButton TWallet;
    private javax.swing.JLabel dCno;
    private javax.swing.JLabel dName;
    private javax.swing.JLabel dPno;
    private javax.swing.JLabel dRating;
    private javax.swing.JLabel duration;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel pickup1;
    private javax.swing.JLabel returnCB;
    private javax.swing.JLabel tamt;
    private javax.swing.JLabel trips_completed;
    // End of variables declaration//GEN-END:variables
}
